services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    depends_on:
    - web_service
    ports:
    - "8000:8000"
    - "8001:8001"
    - "8002:8002"
    - "8003:8003"
    - "9901:9901"

  web_service:
    environment:
    - PORT=9000
    build:
      context: ../shared/echo
